version: '2'
services:

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus-data:/prometheus-data

  cadvisor:
    image: google/cadvisor:latest
    ports:
      - 9080:8080

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - ./grafana:/var/lib/grafana
